### PR TITLE
Simplify memory declaration in @RegisterAiService

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Review by cescoffier — COMMENTED** [review]
I think the samples need to be fixed.

**Review by cescoffier — APPROVED** [review]

**Comment by geoand** [comment]
Would you like me to do that as part of the PR or should we take care of it later?

**Comment by cescoffier** [comment]
/i cna take care of it later. I want to try the new GPT4 turbo thingy too.

**Comment by geoand** [comment]
👌

**Pull request merged**
