### PR TITLE
Redis improvements

### PR DESCRIPTION
**Pull request by jmartisk**
- use the high level data source api for index creation and searching
- reuse related enums from the Quarkus repo
depends on  https://github.com/quarkusio/quarkus/pull/36939/files

### CODE REVIEW

**Comment by geoand** [comment]
What's the status of this one?

BTW, if you rebase onto main, we now have CI running thanks to @cescoffier

**Comment by jmartisk** [comment]
Working CI maybe, but not in this case since I'm using stuff from https://github.com/quarkusio/quarkus/pull/36939 which will be in Quarkus 3.6, so looks like we might have to wait

**Comment by geoand** [comment]
Ah, I see. In that case, yeah, we'll have to wait to get this in

**Comment by geoand** [comment]
This will have to be redone against https://github.com/quarkiverse/quarkus-langchain4j

**Pull request closed without merging**
