### PR TITLE
Make the chroma store singleton

### PR DESCRIPTION
**Pull request by jmartisk**

### CODE REVIEW

**Comment by geoand** [comment]
I would like to know how this fixes the problem :)

**Comment by cescoffier** [comment]
It fixes the issue... but why?

**Comment by jmartisk** [comment]
I don't fully understand it here.
But the hang is in the blocking REST call to create the collection.  The call is inside the constructor of the CDI bean.
When the bean is application scoped, then the REST call is made lazily in the context of the caller who first injects and calls the bean. For some reason, the REST call hangs.
When the bean is singleton, the constructor and REST call are made in the context of initializing the application, and it works.

**Comment by geoand** [comment]
This may be hidding something more sinister, so I'll take a look later

**Comment by cescoffier** [comment]
Yeah, I feel like something is taking the lock on the proxy. If it's singleton you get the real lock. If you use a proxy, you don't, and you may break the synchronization protocol.

**Comment by geoand** [comment]
I'll close this in favor of 87d440237c27145f39f99ba9ed3c78129e39c9e0

**Pull request closed without merging**
